### ISSUE TITLE
TestA.app build failed

### ISSUE THREAD

**Issue by nanier** [gatzsche/LSApplicationQueriesSchemes-Working-Example#2]
TestALaunchScreen.storyboard may not be set custom classnames. Because the viewController in TestALaunchScreen.storyboard is set to "TestAViewController",click the identity inspector of the viewController, remove the custom class, the TestA.app build succeed.
![image](https://cloud.githubusercontent.com/assets/3774789/11418640/b1cef8fe-945c-11e5-8aeb-1528079fef0b.png)

**Comment by gatzsche** [comment]
Thank you very much for reporting this. I have fixed this and pushed.
